name: qumyrsqa_tamga
description: Qumyrsqa Tamga — Hardware-anchored data trust layer demo

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  crypto: ^3.0.3
  device_info_plus: ^11.1.1
  sensors_plus: ^6.1.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  file_picker: ^8.0.0
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
